version: '3.8'

services:
  webtestex_redis:
    container_name: webtestexredis
    build:
      context: .
      dockerfile: WebTestEx_Redis/Dockerfile
    ports:
      - "8011:80" 
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379

  # redis-admin:
  #   image: marian/rebrow
  #   ports:
  #     - 5001:5001
  #   depends_on:
  #     - redis