version: '3.8'

services:
    webredisex:
        build:
          context: .
          dockerfile: WebRedisEx/Dockerfile
        ports:
          - "5001:80"
        depends_on:
          - redis123
    redis123:
        image: "redis"
        ports:
          - "6379:6379"